// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using QRiMovWeb.Context;
using System;

namespace QRiMovWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200520103157_MigracaoInicial2")]
    partial class MigracaoInicial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QRiMovWeb.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoriaNome")
                        .HasMaxLength(100);

                    b.Property<string>("Descricao")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("QRiMovWeb.Models.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro")
                        .HasMaxLength(50);

                    b.Property<string>("CEP")
                        .HasMaxLength(20);

                    b.Property<int>("CategoriaId");

                    b.Property<string>("Comarca")
                        .HasMaxLength(200);

                    b.Property<string>("Complemento")
                        .HasMaxLength(50);

                    b.Property<string>("Descricao")
                        .HasMaxLength(255);

                    b.Property<string>("ImgMiniaturaUrl")
                        .HasMaxLength(255);

                    b.Property<string>("ImgUrl")
                        .HasMaxLength(255);

                    b.Property<bool>("IsAtivo");

                    b.Property<bool>("IsDestaque");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(255);

                    b.Property<string>("Numero")
                        .HasMaxLength(30);

                    b.Property<string>("UF")
                        .HasMaxLength(2);

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Imoveis");
                });

            modelBuilder.Entity("QRiMovWeb.Models.Imovel", b =>
                {
                    b.HasOne("QRiMovWeb.Models.Categoria", "Categoria")
                        .WithMany("Imoveis")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
